/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serviceprovidingsystem.UserWindows;
import serviceprovidingsystem.MapAndAnimation.Animations;
import serviceprovidingsystem.*;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import serviceprovidingsystem.Database.DatabaseConnection;

/**
 *
 * @author omer
 */
public class HomeWindow extends javax.swing.JFrame {

    /**
     * Creates new form HomeWindow
     */
    //attribute
    DatabaseConnection database;
    //setting panel
        private boolean isSandwhichSettingPanelOpen = false;
        private int widthOfSettingPanel;
        private int heightOfSettingPanel;
    //WorkerSelection
        private boolean isElectrician = false;
        private boolean isLabour = false;
        private boolean isEventManager = false;
        private boolean isMechanic = false;
        private boolean isPlumber = false;
    //Movable HomeBarPanel
        int XMouse;
        int YMouse;
    //Option button Pricing
        double option1=0, option2=0, option3=0, option4=0;
        double totalCost;

        
    public HomeWindow(){
        initComponents();
    }
    public HomeWindow(DatabaseConnection database) {
        initComponents();
        this.database = database;
        btnCloseJobOptions.setVisible(false);//not show close btn until selection
        this.setBackground(new Color(0,0,0,0));
        this.setOpacity(0f);
        this.setLocationRelativeTo(null);
        this.sandwichSettingPanel.setVisible(false);
        widthOfSettingPanel =  this.sandwichSettingPanel.getWidth();
        heightOfSettingPanel = this.sandwichSettingPanel.getHeight();
        optionLabel1.setVisible(false);
        optionLabel2.setVisible(false);
        optionLabel3.setVisible(false);
        optionLabel4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        logoBar = new com.k33ptoo.components.KGradientPanel();
        closeBar = new com.k33ptoo.components.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        tItleBar = new com.k33ptoo.components.KGradientPanel();
        homeBar = new javax.swing.JLabel();
        sandwichSettingPanel = new com.k33ptoo.components.KGradientPanel();
        signOutBtn1 = new com.k33ptoo.components.KButton();
        btnSettingPassword = new com.k33ptoo.components.KButton();
        signOutBtn4 = new com.k33ptoo.components.KButton();
        btnSettingNumber = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();
        homeBackgroundPanel = new com.k33ptoo.components.KGradientPanel();
        kGradientPanel5 = new com.k33ptoo.components.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        kGradientPanel10 = new com.k33ptoo.components.KGradientPanel();
        kGradientPanel12 = new com.k33ptoo.components.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        kGradientPanel18 = new com.k33ptoo.components.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        kGradientPanel13 = new com.k33ptoo.components.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        kGradientPanel17 = new com.k33ptoo.components.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();
        SelectOptionsWindow = new com.k33ptoo.components.KGradientPanel();
        btnJobType3 = new com.k33ptoo.components.KButton();
        workderJobLabel = new javax.swing.JLabel();
        btnJobType1 = new com.k33ptoo.components.KButton();
        btnJobType2 = new com.k33ptoo.components.KButton();
        btnJobType4 = new com.k33ptoo.components.KButton();
        jobTypeLabel4 = new javax.swing.JLabel();
        jobTypeLabel1 = new javax.swing.JLabel();
        jobTypeLabel2 = new javax.swing.JLabel();
        jobTypeLabel3 = new javax.swing.JLabel();
        btnCloseJobOptions = new javax.swing.JLabel();
        jobSelectedShowLabel = new javax.swing.JLabel();
        optionLabel4 = new javax.swing.JLabel();
        optionLabel1 = new javax.swing.JLabel();
        optionLabel2 = new javax.swing.JLabel();
        optionLabel3 = new javax.swing.JLabel();
        kGradientPanel19 = new com.k33ptoo.components.KGradientPanel();
        jLabel8 = new javax.swing.JLabel();
        btnElectrician = new com.k33ptoo.components.KButton();
        btnPlumber = new com.k33ptoo.components.KButton();
        btnMechanic = new com.k33ptoo.components.KButton();
        btnEventManager = new com.k33ptoo.components.KButton();
        btnLabour = new com.k33ptoo.components.KButton();
        btnUnavailable = new com.k33ptoo.components.KButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1066, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1066, 600));

        logoBar.setkEndColor(new java.awt.Color(24, 25, 25));
        logoBar.setkGradientFocus(50);
        logoBar.setkStartColor(new java.awt.Color(28, 40, 51));
        logoBar.setOpaque(false);

        javax.swing.GroupLayout logoBarLayout = new javax.swing.GroupLayout(logoBar);
        logoBar.setLayout(logoBarLayout);
        logoBarLayout.setHorizontalGroup(
            logoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        logoBarLayout.setVerticalGroup(
            logoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jLayeredPane1.add(logoBar);
        logoBar.setBounds(10, 0, 50, 40);

        closeBar.setkEndColor(new java.awt.Color(24, 25, 25));
        closeBar.setkGradientFocus(50);
        closeBar.setkStartColor(new java.awt.Color(28, 40, 51));
        closeBar.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviceprovidingsystem/images/HomeWindow/close_window_32px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setPreferredSize(new java.awt.Dimension(21, 19));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout closeBarLayout = new javax.swing.GroupLayout(closeBar);
        closeBar.setLayout(closeBarLayout);
        closeBarLayout.setHorizontalGroup(
            closeBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        closeBarLayout.setVerticalGroup(
            closeBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jLayeredPane1.add(closeBar);
        closeBar.setBounds(1010, 0, 40, 40);

        tItleBar.setkEndColor(new java.awt.Color(24, 25, 25));
        tItleBar.setkGradientFocus(1000);
        tItleBar.setkStartColor(new java.awt.Color(28, 40, 51));
        tItleBar.setOpaque(false);

        homeBar.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 24)); // NOI18N
        homeBar.setForeground(new java.awt.Color(255, 255, 255));
        homeBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeBar.setText("Home");
        homeBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                homeBarMouseDragged(evt);
            }
        });
        homeBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeBarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout tItleBarLayout = new javax.swing.GroupLayout(tItleBar);
        tItleBar.setLayout(tItleBarLayout);
        tItleBarLayout.setHorizontalGroup(
            tItleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tItleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBar, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
        );
        tItleBarLayout.setVerticalGroup(
            tItleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tItleBarLayout.createSequentialGroup()
                .addComponent(homeBar, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane1.add(tItleBar);
        tItleBar.setBounds(250, 0, 561, 70);

        sandwichSettingPanel.setkBorderRadius(15);
        sandwichSettingPanel.setkEndColor(new java.awt.Color(60, 156, 220));
        sandwichSettingPanel.setkStartColor(new java.awt.Color(180, 225, 255));
        sandwichSettingPanel.setOpaque(false);
        sandwichSettingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signOutBtn1.setText("Sign Out");
        signOutBtn1.setBorderPainted(false);
        signOutBtn1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        signOutBtn1.setkEndColor(new java.awt.Color(255, 255, 255));
        signOutBtn1.setkForeGround(new java.awt.Color(0, 0, 0));
        signOutBtn1.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        signOutBtn1.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        signOutBtn1.setkHoverStartColor(new java.awt.Color(240, 239, 239));
        signOutBtn1.setkStartColor(new java.awt.Color(255, 255, 255));
        signOutBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutBtn1ActionPerformed(evt);
            }
        });
        sandwichSettingPanel.add(signOutBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 280, 30));

        btnSettingPassword.setText("Password");
        btnSettingPassword.setBorderPainted(false);
        btnSettingPassword.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        btnSettingPassword.setkEndColor(new java.awt.Color(255, 255, 255));
        btnSettingPassword.setkForeGround(new java.awt.Color(0, 0, 0));
        btnSettingPassword.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        btnSettingPassword.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnSettingPassword.setkHoverStartColor(new java.awt.Color(240, 239, 239));
        btnSettingPassword.setkStartColor(new java.awt.Color(255, 255, 255));
        btnSettingPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingPasswordActionPerformed(evt);
            }
        });
        sandwichSettingPanel.add(btnSettingPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 155, 280, 30));

        signOutBtn4.setText("Address");
        signOutBtn4.setBorderPainted(false);
        signOutBtn4.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        signOutBtn4.setkEndColor(new java.awt.Color(255, 255, 255));
        signOutBtn4.setkForeGround(new java.awt.Color(0, 0, 0));
        signOutBtn4.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        signOutBtn4.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        signOutBtn4.setkHoverStartColor(new java.awt.Color(240, 239, 239));
        signOutBtn4.setkStartColor(new java.awt.Color(255, 255, 255));
        sandwichSettingPanel.add(signOutBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 251, 280, 30));

        btnSettingNumber.setText("Mobile number");
        btnSettingNumber.setBorderPainted(false);
        btnSettingNumber.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        btnSettingNumber.setkEndColor(new java.awt.Color(255, 255, 255));
        btnSettingNumber.setkForeGround(new java.awt.Color(0, 0, 0));
        btnSettingNumber.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        btnSettingNumber.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnSettingNumber.setkHoverStartColor(new java.awt.Color(240, 239, 239));
        btnSettingNumber.setkStartColor(new java.awt.Color(255, 255, 255));
        btnSettingNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingNumberActionPerformed(evt);
            }
        });
        sandwichSettingPanel.add(btnSettingNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 203, 280, 30));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviceprovidingsystem/images/HomeWindow/settings_32px.png"))); // NOI18N
        jLabel1.setText("Settings");
        sandwichSettingPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 20, -1, -1));

        jLayeredPane1.add(sandwichSettingPanel);
        sandwichSettingPanel.setBounds(62, 80, 410, 480);

        homeBackgroundPanel.setkBorderRadius(60);
        homeBackgroundPanel.setkEndColor(new java.awt.Color(255, 255, 255));
        homeBackgroundPanel.setkStartColor(new java.awt.Color(255, 255, 255));
        homeBackgroundPanel.setOpaque(false);

        kGradientPanel5.setkBorderRadius(50);
        kGradientPanel5.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel5.setkStartColor(new java.awt.Color(28, 40, 51));
        kGradientPanel5.setOpaque(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviceprovidingsystem/images/HomeWindow/sandwichMenu_32x.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviceprovidingsystem/images/HomeWindow/contactUs_32x.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel2))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(25, 25, 25))
        );

        kGradientPanel10.setkBorderRadius(0);
        kGradientPanel10.setkEndColor(new java.awt.Color(230, 126, 34));
        kGradientPanel10.setkStartColor(new java.awt.Color(255, 229, 205));
        kGradientPanel10.setOpaque(false);
        kGradientPanel10.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout kGradientPanel10Layout = new javax.swing.GroupLayout(kGradientPanel10);
        kGradientPanel10.setLayout(kGradientPanel10Layout);
        kGradientPanel10Layout.setHorizontalGroup(
            kGradientPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        kGradientPanel10Layout.setVerticalGroup(
            kGradientPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        kGradientPanel12.setkEndColor(new java.awt.Color(84, 166, 220));
        kGradientPanel12.setkStartColor(new java.awt.Color(199, 232, 253));
        kGradientPanel12.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Name                   Job                   Experience                   Rating ");

        javax.swing.GroupLayout kGradientPanel12Layout = new javax.swing.GroupLayout(kGradientPanel12);
        kGradientPanel12.setLayout(kGradientPanel12Layout);
        kGradientPanel12Layout.setHorizontalGroup(
            kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel12Layout.setVerticalGroup(
            kGradientPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        kGradientPanel18.setkBorderRadius(20);
        kGradientPanel18.setkEndColor(new java.awt.Color(204, 204, 204));
        kGradientPanel18.setkStartColor(new java.awt.Color(240, 240, 240));
        kGradientPanel18.setOpaque(false);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviceprovidingsystem/images/HomeWindow/5rating.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel18Layout = new javax.swing.GroupLayout(kGradientPanel18);
        kGradientPanel18.setLayout(kGradientPanel18Layout);
        kGradientPanel18Layout.setHorizontalGroup(
            kGradientPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        kGradientPanel18Layout.setVerticalGroup(
            kGradientPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel13.setkBorderRadius(20);
        kGradientPanel13.setkEndColor(new java.awt.Color(204, 204, 204));
        kGradientPanel13.setkStartColor(new java.awt.Color(240, 240, 240));
        kGradientPanel13.setOpaque(false);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviceprovidingsystem/images/HomeWindow/45rating.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel13Layout = new javax.swing.GroupLayout(kGradientPanel13);
        kGradientPanel13.setLayout(kGradientPanel13Layout);
        kGradientPanel13Layout.setHorizontalGroup(
            kGradientPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        kGradientPanel13Layout.setVerticalGroup(
            kGradientPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel17.setkBorderRadius(20);
        kGradientPanel17.setkEndColor(new java.awt.Color(204, 204, 204));
        kGradientPanel17.setkStartColor(new java.awt.Color(240, 240, 240));
        kGradientPanel17.setOpaque(false);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviceprovidingsystem/images/HomeWindow/4rating.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel17Layout = new javax.swing.GroupLayout(kGradientPanel17);
        kGradientPanel17.setLayout(kGradientPanel17Layout);
        kGradientPanel17Layout.setHorizontalGroup(
            kGradientPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        kGradientPanel17Layout.setVerticalGroup(
            kGradientPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SelectOptionsWindow.setkBorderRadius(15);
        SelectOptionsWindow.setkEndColor(new java.awt.Color(60, 156, 220));
        SelectOptionsWindow.setkStartColor(new java.awt.Color(180, 225, 255));
        SelectOptionsWindow.setOpaque(false);
        SelectOptionsWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJobType3.setBorderPainted(false);
        btnJobType3.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        btnJobType3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnJobType3.setkEndColor(new java.awt.Color(255, 255, 255));
        btnJobType3.setkForeGround(new java.awt.Color(0, 0, 0));
        btnJobType3.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        btnJobType3.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnJobType3.setkHoverStartColor(new java.awt.Color(240, 239, 239));
        btnJobType3.setkStartColor(new java.awt.Color(255, 255, 255));
        btnJobType3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobType3ActionPerformed(evt);
            }
        });
        SelectOptionsWindow.add(btnJobType3, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 285, 60, -1));

        workderJobLabel.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        workderJobLabel.setForeground(new java.awt.Color(28, 40, 51));
        workderJobLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectOptionsWindow.add(workderJobLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 43, 410, 40));

        btnJobType1.setBorderPainted(false);
        btnJobType1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        btnJobType1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnJobType1.setkEndColor(new java.awt.Color(255, 255, 255));
        btnJobType1.setkForeGround(new java.awt.Color(0, 0, 0));
        btnJobType1.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        btnJobType1.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnJobType1.setkHoverStartColor(new java.awt.Color(240, 239, 239));
        btnJobType1.setkStartColor(new java.awt.Color(255, 255, 255));
        btnJobType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobType1ActionPerformed(evt);
            }
        });
        SelectOptionsWindow.add(btnJobType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 105, 60, -1));

        btnJobType2.setBorderPainted(false);
        btnJobType2.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        btnJobType2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnJobType2.setkEndColor(new java.awt.Color(255, 255, 255));
        btnJobType2.setkForeGround(new java.awt.Color(0, 0, 0));
        btnJobType2.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        btnJobType2.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnJobType2.setkHoverStartColor(new java.awt.Color(240, 239, 239));
        btnJobType2.setkStartColor(new java.awt.Color(255, 255, 255));
        btnJobType2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobType2ActionPerformed(evt);
            }
        });
        SelectOptionsWindow.add(btnJobType2, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 194, 60, -1));

        btnJobType4.setBorderPainted(false);
        btnJobType4.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        btnJobType4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnJobType4.setkEndColor(new java.awt.Color(255, 255, 255));
        btnJobType4.setkForeGround(new java.awt.Color(0, 0, 0));
        btnJobType4.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        btnJobType4.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnJobType4.setkHoverStartColor(new java.awt.Color(240, 239, 239));
        btnJobType4.setkStartColor(new java.awt.Color(255, 255, 255));
        btnJobType4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobType4ActionPerformed(evt);
            }
        });
        SelectOptionsWindow.add(btnJobType4, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 380, 60, -1));

        jobTypeLabel4.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 15)); // NOI18N
        jobTypeLabel4.setForeground(new java.awt.Color(28, 40, 51));
        SelectOptionsWindow.add(jobTypeLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 270, 40));

        jobTypeLabel1.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 15)); // NOI18N
        jobTypeLabel1.setForeground(new java.awt.Color(28, 40, 51));
        SelectOptionsWindow.add(jobTypeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 270, 40));

        jobTypeLabel2.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 15)); // NOI18N
        jobTypeLabel2.setForeground(new java.awt.Color(28, 40, 51));
        SelectOptionsWindow.add(jobTypeLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 270, 40));

        jobTypeLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 15)); // NOI18N
        jobTypeLabel3.setForeground(new java.awt.Color(28, 40, 51));
        SelectOptionsWindow.add(jobTypeLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 310, 40));

        btnCloseJobOptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviceprovidingsystem/images/HomeWindow/closeJobIcon_32px.png"))); // NOI18N
        btnCloseJobOptions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCloseJobOptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseJobOptionsMouseClicked(evt);
            }
        });
        SelectOptionsWindow.add(btnCloseJobOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 30, 30));

        jobSelectedShowLabel.setForeground(new java.awt.Color(28, 40, 51));
        jobSelectedShowLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jobSelectedShowLabel.setText("-");
        SelectOptionsWindow.add(jobSelectedShowLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 456, 380, 40));

        optionLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviceprovidingsystem/images/HomeWindow/checkmark_16px.png"))); // NOI18N
        SelectOptionsWindow.add(optionLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, 40));

        optionLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviceprovidingsystem/images/HomeWindow/checkmark_16px.png"))); // NOI18N
        SelectOptionsWindow.add(optionLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, 40));

        optionLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviceprovidingsystem/images/HomeWindow/checkmark_16px.png"))); // NOI18N
        SelectOptionsWindow.add(optionLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, 40));

        optionLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviceprovidingsystem/images/HomeWindow/checkmark_16px.png"))); // NOI18N
        SelectOptionsWindow.add(optionLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, 40));

        kGradientPanel19.setkBorderRadius(20);
        kGradientPanel19.setkEndColor(new java.awt.Color(204, 204, 204));
        kGradientPanel19.setkStartColor(new java.awt.Color(240, 240, 240));
        kGradientPanel19.setOpaque(false);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviceprovidingsystem/images/HomeWindow/4rating.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel19Layout = new javax.swing.GroupLayout(kGradientPanel19);
        kGradientPanel19.setLayout(kGradientPanel19Layout);
        kGradientPanel19Layout.setHorizontalGroup(
            kGradientPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        kGradientPanel19Layout.setVerticalGroup(
            kGradientPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnElectrician.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviceprovidingsystem/images/HomeWindow/electricianIcon.png"))); // NOI18N
        btnElectrician.setBorderPainted(false);
        btnElectrician.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        btnElectrician.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnElectrician.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnElectrician.setIconTextGap(35);
        btnElectrician.setkEndColor(new java.awt.Color(60, 156, 220));
        btnElectrician.setkForeGround(new java.awt.Color(0, 0, 0));
        btnElectrician.setkHoverEndColor(new java.awt.Color(180, 225, 255));
        btnElectrician.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnElectrician.setkHoverStartColor(new java.awt.Color(180, 225, 255));
        btnElectrician.setkPressedColor(new java.awt.Color(207, 233, 250));
        btnElectrician.setkStartColor(new java.awt.Color(180, 225, 255));
        btnElectrician.setPreferredSize(new java.awt.Dimension(119, 125));
        btnElectrician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElectricianActionPerformed(evt);
            }
        });

        btnPlumber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviceprovidingsystem/images/HomeWindow/plumberIcon.png"))); // NOI18N
        btnPlumber.setBorderPainted(false);
        btnPlumber.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        btnPlumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPlumber.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnPlumber.setIconTextGap(35);
        btnPlumber.setkEndColor(new java.awt.Color(60, 156, 220));
        btnPlumber.setkForeGround(new java.awt.Color(0, 0, 0));
        btnPlumber.setkHoverEndColor(new java.awt.Color(180, 225, 255));
        btnPlumber.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnPlumber.setkHoverStartColor(new java.awt.Color(180, 225, 255));
        btnPlumber.setkPressedColor(new java.awt.Color(207, 233, 250));
        btnPlumber.setkStartColor(new java.awt.Color(180, 225, 255));
        btnPlumber.setPreferredSize(new java.awt.Dimension(119, 125));
        btnPlumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlumberActionPerformed(evt);
            }
        });

        btnMechanic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviceprovidingsystem/images/HomeWindow/mechanicIcon.png"))); // NOI18N
        btnMechanic.setBorderPainted(false);
        btnMechanic.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        btnMechanic.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMechanic.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnMechanic.setIconTextGap(35);
        btnMechanic.setkEndColor(new java.awt.Color(60, 156, 220));
        btnMechanic.setkForeGround(new java.awt.Color(0, 0, 0));
        btnMechanic.setkHoverEndColor(new java.awt.Color(180, 225, 255));
        btnMechanic.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnMechanic.setkHoverStartColor(new java.awt.Color(180, 225, 255));
        btnMechanic.setkPressedColor(new java.awt.Color(207, 233, 250));
        btnMechanic.setkStartColor(new java.awt.Color(180, 225, 255));
        btnMechanic.setPreferredSize(new java.awt.Dimension(119, 125));
        btnMechanic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMechanicActionPerformed(evt);
            }
        });

        btnEventManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviceprovidingsystem/images/HomeWindow/eventManagerIcon.png"))); // NOI18N
        btnEventManager.setBorderPainted(false);
        btnEventManager.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        btnEventManager.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEventManager.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnEventManager.setIconTextGap(35);
        btnEventManager.setkEndColor(new java.awt.Color(60, 156, 220));
        btnEventManager.setkForeGround(new java.awt.Color(0, 0, 0));
        btnEventManager.setkHoverEndColor(new java.awt.Color(180, 225, 255));
        btnEventManager.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnEventManager.setkHoverStartColor(new java.awt.Color(180, 225, 255));
        btnEventManager.setkPressedColor(new java.awt.Color(207, 233, 250));
        btnEventManager.setkStartColor(new java.awt.Color(180, 225, 255));
        btnEventManager.setPreferredSize(new java.awt.Dimension(119, 125));
        btnEventManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventManagerActionPerformed(evt);
            }
        });

        btnLabour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/serviceprovidingsystem/images/HomeWindow/labourIcon.png"))); // NOI18N
        btnLabour.setBorderPainted(false);
        btnLabour.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        btnLabour.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLabour.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLabour.setIconTextGap(35);
        btnLabour.setkEndColor(new java.awt.Color(60, 156, 220));
        btnLabour.setkForeGround(new java.awt.Color(0, 0, 0));
        btnLabour.setkHoverEndColor(new java.awt.Color(180, 225, 255));
        btnLabour.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnLabour.setkHoverStartColor(new java.awt.Color(180, 225, 255));
        btnLabour.setkPressedColor(new java.awt.Color(207, 233, 250));
        btnLabour.setkStartColor(new java.awt.Color(180, 225, 255));
        btnLabour.setPreferredSize(new java.awt.Dimension(119, 125));
        btnLabour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabourActionPerformed(evt);
            }
        });

        btnUnavailable.setText("Coming Soon");
        btnUnavailable.setBorderPainted(false);
        btnUnavailable.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        btnUnavailable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUnavailable.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnUnavailable.setIconTextGap(35);
        btnUnavailable.setkEndColor(new java.awt.Color(60, 156, 220));
        btnUnavailable.setkForeGround(new java.awt.Color(0, 0, 0));
        btnUnavailable.setkHoverEndColor(new java.awt.Color(180, 225, 255));
        btnUnavailable.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnUnavailable.setkHoverStartColor(new java.awt.Color(180, 225, 255));
        btnUnavailable.setkPressedColor(new java.awt.Color(207, 233, 250));
        btnUnavailable.setkStartColor(new java.awt.Color(180, 225, 255));
        btnUnavailable.setPreferredSize(new java.awt.Dimension(119, 125));
        btnUnavailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnavailableActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Electrician");

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Mechanic");

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Labour");

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Plumber");

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Event Manager");

        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Not Available");

        javax.swing.GroupLayout homeBackgroundPanelLayout = new javax.swing.GroupLayout(homeBackgroundPanel);
        homeBackgroundPanel.setLayout(homeBackgroundPanelLayout);
        homeBackgroundPanelLayout.setHorizontalGroup(
            homeBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBackgroundPanelLayout.createSequentialGroup()
                .addComponent(kGradientPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(homeBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(homeBackgroundPanelLayout.createSequentialGroup()
                        .addGroup(homeBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPlumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnElectrician, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(homeBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMechanic, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnEventManager, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(homeBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLabour, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnUnavailable, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(kGradientPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kGradientPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kGradientPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kGradientPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kGradientPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .addComponent(kGradientPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(SelectOptionsWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        homeBackgroundPanelLayout.setVerticalGroup(
            homeBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBackgroundPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(homeBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SelectOptionsWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(homeBackgroundPanelLayout.createSequentialGroup()
                        .addGroup(homeBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homeBackgroundPanelLayout.createSequentialGroup()
                                .addGroup(homeBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMechanic, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLabour, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(homeBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(homeBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEventManager, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUnavailable, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(homeBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(homeBackgroundPanelLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel13))
                                    .addGroup(homeBackgroundPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15))))
                            .addGroup(homeBackgroundPanelLayout.createSequentialGroup()
                                .addComponent(btnElectrician, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPlumber, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kGradientPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kGradientPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kGradientPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kGradientPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kGradientPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kGradientPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(kGradientPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        kGradientPanel10.getAccessibleContext().setAccessibleName("");

        jLayeredPane1.add(homeBackgroundPanel);
        homeBackgroundPanel.setBounds(0, 50, 1070, 552);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        if(isSandwhichSettingPanelOpen){
            Animations.panelCloseAnimation(this.sandwichSettingPanel,widthOfSettingPanel,heightOfSettingPanel);
            isSandwhichSettingPanelOpen = false;
        } else{
            Animations.panelAppearAnimation(this.sandwichSettingPanel,widthOfSettingPanel,heightOfSettingPanel);
            isSandwhichSettingPanelOpen = true;
        }
            
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Animations.windowExitAnimation(this, 1f);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void signOutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutBtn1ActionPerformed
        // TODO add your handling code here:
        
        Animations.windowCloseAnimation(this, 1f);
        new SignInWindow(database).setVisible(true);
    }//GEN-LAST:event_signOutBtn1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Animations.windowAppearAnimation(this, 1f);
    }//GEN-LAST:event_formWindowOpened

    private void btnElectricianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElectricianActionPerformed
        // TODO add your handling code here:
        //if setting panel is open button still works so i made a if statment
        //so that while open setting panel button behind it won't run.
        if(isSandwhichSettingPanelOpen){
            //dont code here
        } else {
            //code here
            workderJobLabel.setText("Electrician");
            optionLabelsSetToFalse();
            btnCloseJobOptions.setVisible(true);
            isElectrician = true;
            isPlumber = false;
            isMechanic = false;
            isEventManager = false;
            isLabour = false;
            option1 = 500;
            option2 = 1000;
            option3 = 1200;
            option4 = 6000;
            jobTypeLabel1.setText("Fault Diagnosis");
            btnJobType1.setText(String.valueOf(option1));
            jobTypeLabel2.setText("Device Installation");
            btnJobType2.setText(String.valueOf(option2));
            jobTypeLabel3.setText("Replacement High Voltage Switch Board");
            btnJobType3.setText(String.valueOf(option3));
            jobTypeLabel4.setText("Air Condition Installation");
            btnJobType4.setText(String.valueOf(option4));

        }
    }//GEN-LAST:event_btnElectricianActionPerformed

    private void btnPlumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlumberActionPerformed
        // TODO add your handling code here:
        //if setting panel is open button still works so i made a if statment
        //so that while open setting panel button behind it won't run.
        if(isSandwhichSettingPanelOpen){
            //dont code here
        } else {
            //coder here
            workderJobLabel.setText("Plumber");
            optionLabelsSetToFalse();
            btnCloseJobOptions.setVisible(true);
            isElectrician = false;
            isPlumber = true;
            isMechanic = false;
            isEventManager = false;
            isLabour = false;
            option1 = 1000;
            option2 = 2000;
            option3 = 6000;
            option4 = 15000;
            jobTypeLabel1.setText("Basic Plumbing(Taps and Piping)");
            btnJobType1.setText(String.valueOf(option1));
            jobTypeLabel2.setText("Sanitary Ware Installation");
            btnJobType2.setText(String.valueOf(option2));
            jobTypeLabel3.setText("Gas and Kitchen Piping");
            btnJobType3.setText(String.valueOf(option3));
            jobTypeLabel4.setText("Full Room through wall Piping");
            btnJobType4.setText(String.valueOf(option4));
 
        }
    }//GEN-LAST:event_btnPlumberActionPerformed

    private void btnMechanicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMechanicActionPerformed
        // TODO add your handling code here:
        //if setting panel is open button still works so i made a if statment
        //so that while open setting panel button behind it won't run.
        if(isSandwhichSettingPanelOpen){
            //dont code here
        } else {
            //coder here
            workderJobLabel.setText("Mechanic");
            optionLabelsSetToFalse();
            btnCloseJobOptions.setVisible(true);
            isElectrician = false;
            isPlumber = false;
            isMechanic = true;
            isEventManager = false;
            isLabour = false;
            option1 = 1000;
            option2 = 800;
            option3 = 2000;
            option4 = 4000;
            jobTypeLabel1.setText("Car Fault Diagnosis");
            btnJobType1.setText(String.valueOf(option1));
            jobTypeLabel2.setText("Petrol Delivery and Emergency Help");
            btnJobType2.setText(String.valueOf(option2));
            jobTypeLabel3.setText("Car Battery/Tire/Oil Replacement");
            btnJobType3.setText(String.valueOf(option3));
            jobTypeLabel4.setText("Full Car Service");
            btnJobType4.setText(String.valueOf(option4));
            
        }
    }//GEN-LAST:event_btnMechanicActionPerformed

    private void btnEventManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventManagerActionPerformed
        // TODO add your handling code here:
        //if setting panel is open button still works so i made a if statment
        //so that while open setting panel button behind it won't run.
        if(isSandwhichSettingPanelOpen){
            //dont code here
        } else {
            //code here
            workderJobLabel.setText("Event Manager");
            optionLabelsSetToFalse();
            btnCloseJobOptions.setVisible(true);
            isElectrician = false;
            isPlumber = false;
            isMechanic = false;
            isEventManager = true;
            isLabour = false;
            option1 = 20000;
            option2 = 50000;
            option3 = 30000;
            option4 = 40000;
            jobTypeLabel1.setText("Houseparty Managment");
            btnJobType1.setText(String.valueOf(option1));
            jobTypeLabel2.setText("Wedding Managment");
            btnJobType2.setText(String.valueOf(option2));
            jobTypeLabel3.setText("University Event Managment");
            btnJobType3.setText(String.valueOf(option3));
            jobTypeLabel4.setText("Public Event Management");
            btnJobType4.setText(String.valueOf(option4));
            
        }
    }//GEN-LAST:event_btnEventManagerActionPerformed

    private void btnLabourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabourActionPerformed
        // TODO add your handling code here:
        //if setting panel is open button still works so i made a if statment
        //so that while open setting panel button behind it won't run.
        if(isSandwhichSettingPanelOpen){
            //dont code here
        } else {
            workderJobLabel.setText("Labour");
            optionLabelsSetToFalse();
            btnCloseJobOptions.setVisible(true);
            isElectrician = false;
            isPlumber = false;
            isMechanic = false;
            isEventManager = false;
            isLabour = true;
            option1 = 5000;
            option2 = 30000;
            option3 = 40000;
            option4 = 60000;
            jobTypeLabel1.setText("House Structural Fixes");
            btnJobType1.setText(String.valueOf(option1));
            jobTypeLabel2.setText("Full Room Tiling");
            btnJobType2.setText(String.valueOf(option2));
            jobTypeLabel3.setText("Wall/Roof Construction(2 Labours)");
            btnJobType3.setText(String.valueOf(option3));
            jobTypeLabel4.setText("Full Room Construction(4 Labours)");
            btnJobType4.setText(String.valueOf(option4));
            
            
            
        }
    }//GEN-LAST:event_btnLabourActionPerformed

    private void homeBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - XMouse, y - YMouse);
    }//GEN-LAST:event_homeBarMouseDragged

    private void homeBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBarMousePressed
        // TODO add your handling code here:
        XMouse = evt.getX() + (int) homeBackgroundPanel.getX()+ 255;
        YMouse = evt.getY() + (int) homeBackgroundPanel.getY() - 50;
    }//GEN-LAST:event_homeBarMousePressed
     
    private void optionLabelsSetToFalse(){
            optionLabel1.setVisible(false);
            optionLabel2.setVisible(false);
            optionLabel3.setVisible(false);
            optionLabel4.setVisible(false);
    }
    
    private void btnJobTypeSetToNull(){
            btnJobType1.setText(String.valueOf(""));
            btnJobType2.setText(String.valueOf(""));
            btnJobType3.setText(String.valueOf(""));
            btnJobType4.setText(String.valueOf(""));
    }
    
    private void jobTypeLabelSetToNull(){
            jobTypeLabel1.setText("");
            jobTypeLabel2.setText("");
            jobTypeLabel3.setText("");
            jobTypeLabel4.setText("");
    }
       
    private void btnUnavailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnavailableActionPerformed
        // TODO add your handling code here:
        //CLOSE THE OPTIONS
        if(isSandwhichSettingPanelOpen){
            //dont code here
        } else {
            isElectrician = false;
            isPlumber = false;
            isMechanic = false;
            isEventManager = false;
            isLabour = false;
            jobTypeLabelSetToNull();
            btnJobTypeSetToNull();
            optionLabelsSetToFalse();
            workderJobLabel.setText("");
            btnCloseJobOptions.setVisible(false);
        }
    }//GEN-LAST:event_btnUnavailableActionPerformed

    private void btnCloseJobOptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseJobOptionsMouseClicked
        // TODO add your handling code here:
        //CLOSE THE OPTIONS
        if(isSandwhichSettingPanelOpen){
            //dont code here
        } else {
            isElectrician = false;
            isPlumber = false;
            isMechanic = false;
            isEventManager = false;
            isLabour = false;
            jobTypeLabelSetToNull();
            btnJobTypeSetToNull();
            optionLabelsSetToFalse();
            workderJobLabel.setText("");
            btnCloseJobOptions.setVisible(false);
        }
    }//GEN-LAST:event_btnCloseJobOptionsMouseClicked

    private void btnSettingPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingPasswordActionPerformed
        // TODO add your handling code here:
        new SettingPanel(database).setVisible(true);//open setting panel
    }//GEN-LAST:event_btnSettingPasswordActionPerformed

    private void btnSettingNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingNumberActionPerformed
        // TODO add your handling code here:
        btnSettingPasswordActionPerformed(evt);//open same setting panel
    }//GEN-LAST:event_btnSettingNumberActionPerformed

    private void btnJobType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobType1ActionPerformed
        // TODO add your handling code here:
        
        if(isElectrician){
            optionLabel1.setVisible(true);
        } else if(isMechanic) {
            optionLabel1.setVisible(true);
        } else if(isLabour) {
            optionLabel1.setVisible(true);
        } else if(isPlumber) {
            optionLabel1.setVisible(true);
        } else if(isEventManager) {
            optionLabel1.setVisible(true);
        } else {
            return;
        }
    }//GEN-LAST:event_btnJobType1ActionPerformed

    private void btnJobType2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobType2ActionPerformed
        // TODO add your handling code here:
        
        if(isElectrician){
            optionLabel2.setVisible(true);
        } else if(isMechanic) {
            optionLabel2.setVisible(true);
        } else if(isLabour) {
            optionLabel2.setVisible(true);
        } else if(isPlumber) {
            optionLabel2.setVisible(true);
        } else if(isEventManager) {
            optionLabel2.setVisible(true);
        } else {
            return;
        }
    }//GEN-LAST:event_btnJobType2ActionPerformed

    private void btnJobType3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobType3ActionPerformed
        // TODO add your handling code here:
        
        if(isElectrician){
            optionLabel3.setVisible(true);
        } else if(isMechanic) {
            optionLabel3.setVisible(true);
        } else if(isLabour) {
            optionLabel3.setVisible(true);
        } else if(isPlumber) {
            optionLabel3.setVisible(true);
        } else if(isEventManager) {
            optionLabel3.setVisible(true);
        } else {
            return;
        }
    }//GEN-LAST:event_btnJobType3ActionPerformed

    private void btnJobType4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobType4ActionPerformed
        // TODO add your handling code here:
        
        if(isElectrician){
            optionLabel4.setVisible(true);
        } else if(isMechanic) {
            optionLabel4.setVisible(true);
        } else if(isLabour) {
            optionLabel4.setVisible(true);
        } else if(isPlumber) {
            optionLabel4.setVisible(true);
        } else if(isEventManager) {
            optionLabel4.setVisible(true);
        } else {
            return;
        }
    }//GEN-LAST:event_btnJobType4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeWindow(new DatabaseConnection()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KGradientPanel SelectOptionsWindow;
    private javax.swing.JLabel btnCloseJobOptions;
    private com.k33ptoo.components.KButton btnElectrician;
    private com.k33ptoo.components.KButton btnEventManager;
    private com.k33ptoo.components.KButton btnJobType1;
    private com.k33ptoo.components.KButton btnJobType2;
    private com.k33ptoo.components.KButton btnJobType3;
    private com.k33ptoo.components.KButton btnJobType4;
    private com.k33ptoo.components.KButton btnLabour;
    private com.k33ptoo.components.KButton btnMechanic;
    private com.k33ptoo.components.KButton btnPlumber;
    private com.k33ptoo.components.KButton btnSettingNumber;
    private com.k33ptoo.components.KButton btnSettingPassword;
    private com.k33ptoo.components.KButton btnUnavailable;
    private com.k33ptoo.components.KGradientPanel closeBar;
    private com.k33ptoo.components.KGradientPanel homeBackgroundPanel;
    private javax.swing.JLabel homeBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel jobSelectedShowLabel;
    private javax.swing.JLabel jobTypeLabel1;
    private javax.swing.JLabel jobTypeLabel2;
    private javax.swing.JLabel jobTypeLabel3;
    private javax.swing.JLabel jobTypeLabel4;
    private com.k33ptoo.components.KGradientPanel kGradientPanel10;
    private com.k33ptoo.components.KGradientPanel kGradientPanel12;
    private com.k33ptoo.components.KGradientPanel kGradientPanel13;
    private com.k33ptoo.components.KGradientPanel kGradientPanel17;
    private com.k33ptoo.components.KGradientPanel kGradientPanel18;
    private com.k33ptoo.components.KGradientPanel kGradientPanel19;
    private com.k33ptoo.components.KGradientPanel kGradientPanel5;
    private com.k33ptoo.components.KGradientPanel logoBar;
    private javax.swing.JLabel optionLabel1;
    private javax.swing.JLabel optionLabel2;
    private javax.swing.JLabel optionLabel3;
    private javax.swing.JLabel optionLabel4;
    private com.k33ptoo.components.KGradientPanel sandwichSettingPanel;
    private com.k33ptoo.components.KButton signOutBtn1;
    private com.k33ptoo.components.KButton signOutBtn4;
    private com.k33ptoo.components.KGradientPanel tItleBar;
    private javax.swing.JLabel workderJobLabel;
    // End of variables declaration//GEN-END:variables
}
